plugins {
    id 'net.neoforged.moddev' version '2.0.140'
}

version = project.mod_version
group = project.mod_group

base {
    archivesName = project.mod_id
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
}

neoForge {
    version = project.neoforge_version

    mods {
        "${project.mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

jar {
    manifest {
        attributes([
            'Specification-Title'     : project.mod_id,
            'Specification-Vendor'    : 'kingmihailp',
            'Specification-Version'   : '1',
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.jar.archiveVersion,
            'Implementation-Vendor'   : 'kingmihailp',
            'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}
